fos_rest:
  body_listener: true
  param_fetcher_listener: force
  format_listener:
    enabled: true
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }
  view:
    view_response_listener: 'force'
    formats:
      json: true
      xml: false
      rss: false
    mime_types:
      json: ['application/json', 'application/x-json']
  routing_loader:
    default_format:  json
    include_format:  false
  exception:
    enabled: true

#fos_user:
#  db_driver: orm
#  firewall_name: api
#  user_class: App\Entity\User
#  from_email:
#    address: rybalkamasha64@gmail.com
#    sender_name: masha

jms_serializer:
  visitors:
    xml:
      format_output: '%kernel.debug%'

lexik_jwt_authentication:
  private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
  public_key_path:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
  pass_phrase:      '%env(JWT_PASSPHRASE)%'
  token_ttl:         3600 #whatever you like
  token_extractors:
    authorization_header: ~
    cookie: ~
    query_parameter: ~