name: Rest-API

on: [push]

jobs:
  production-deploy:
    if: github.repository == 'MaryRybalka/rest_api_prod'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start ${{ github.event_name }} event."

      - run: echo "Start Install dependencies."
      - name: Install dependencies
        run: composer install
      - run: echo "Finish Install dependencies."

      - name: Use PHP-cs-fixer
        run: vendor/bin/php-cs-fixer fix src
      - run: echo "Finish fix src."

      - run: echo "Start Testing."
      - name: Execute tests PHPUnit
        run: vendor/bin/phpunit
      - run: echo "Finish Testing."

  staging-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'MaryRybalka/rest_api'
    steps:
      - run: echo "Start ${{ github.event_name }} event."

      - name: Use PHP-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix src
      - run: echo "Finish fix src."

      - run: echo "Start Testing."
      - name: Execute tests PHPUnit
        run: ./vendor/bin/phpunit
      - run: echo "Finish Testing."