name: Rest-API

on: [push]

jobs:
  unitphp:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start ${{ github.event_name }} event."

      - run: echo "Start Install dependencies."
      - name: Install dependencies
        run: composer install
      - run: echo "Finish Install dependencies."
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - run: echo "Start fix src."
      - name: Use PHP-cs-fixer
        run: vendor/bin/php-cs-fixer fix src
      - run: echo "Finish fix src."

      - run: echo "Start Testing."
      - name: Execute tests PHPUnit
        run: vendor/bin/phpunit
      - run: echo "Finish Testing."
